package example.model;

public class SystemAttr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_attr.id
     *
     * @mbg.generated Thu Jul 16 13:35:45 MSK 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_attr.name
     *
     * @mbg.generated Thu Jul 16 13:35:45 MSK 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_attr.actionind
     *
     * @mbg.generated Thu Jul 16 13:35:45 MSK 2020
     */
    private String actionind;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_attr.id
     *
     * @return the value of system_attr.id
     *
     * @mbg.generated Thu Jul 16 13:35:45 MSK 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_attr.id
     *
     * @param id the value for system_attr.id
     *
     * @mbg.generated Thu Jul 16 13:35:45 MSK 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_attr.name
     *
     * @return the value of system_attr.name
     *
     * @mbg.generated Thu Jul 16 13:35:45 MSK 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_attr.name
     *
     * @param name the value for system_attr.name
     *
     * @mbg.generated Thu Jul 16 13:35:45 MSK 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_attr.actionind
     *
     * @return the value of system_attr.actionind
     *
     * @mbg.generated Thu Jul 16 13:35:45 MSK 2020
     */
    public String getActionind() {
        return actionind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_attr.actionind
     *
     * @param actionind the value for system_attr.actionind
     *
     * @mbg.generated Thu Jul 16 13:35:45 MSK 2020
     */
    public void setActionind(String actionind) {
        this.actionind = actionind;
    }
}