server:
  port: 8881
  servlet:
    context-path: /spring
logging:
  config: 'classpath:log4j2.properties'
  level:
    ru.shaplov: DEBUG
    org:
      springframework: DEBUG
    com.spring.ibatis: DEBUG
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
mybatis:
  type-handlers-package: ru.shaplov.spring.repository.typehandler
#  executor-type: BATCH