server:
  port: 8881
  servlet:
    context-path: /spring
logging:
  config: 'classpath:log4j2.properties'
  level:
    ru.shaplov: DEBUG
    org:
      springframework: DEBUG
    com.spring.ibatis: DEBUG

spring:
  main:
    allow-bean-definition-overriding: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 123456
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: mysecretpassword
    hikari:
      connection-init-sql: SET SEARCH_PATH TO testbd;
    driver-class-name: org.postgresql.Driver
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
    show-sql: true
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: baeldung

mybatis:
  type-handlers-package: ru.shaplov.spring.repository.typehandler
#  executor-type: BATCH

test:
  topic: embedded-test-topic